import = [ "~/dotfiles/alacritty/alacritty-theme/themes/seashells.toml" ]

[env]
TERM = "alacritty"

live_config_reload = "true"

[font]
size = 16

[font.bold]
style = "Regular"

[font.glyph_offset]
y = 7

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.offset]
y = 12

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

