alias heroky="heroku"
alias git="git"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp="git push origin HEAD"
alias gd="git diff"
alias gac="git add -A && git commit -m"
alias gs="git status"
alias gco="git checkout"
alias gsup="git branch --set-upstream-to=origin/$(current_branch)"
alias guncommit="git reset HEAD~1"
# alias artisan="php artisan"
alias art="php artisan"
alias tt="cd ~/Code/tmg/"
alias jj="cd ~/Code/JoseCanHelp/"
alias dot="cd ~/dotfiles"
alias updatedotbot="dot && git submodule update --remote dotbot"
alias gsa="git submodule add"
alias vs="vagrant status"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vd="vagrant destroy"
alias cda="composer dump-autoload"
alias dpostgres="docker run --name postgres -v data:/var/lib/postgresql/data -e POSTGRES_USER=perk -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=myapp -p 5432:5432 -d postgres"
alias dmysql="docker run --name mysql -v mysql_data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret -p 3306:3306 -d mysql:5.7"
alias artclear="php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan route:clear"
alias phpunitd="php -d xdebug.profiler_enable=on vendor/bin/phpunit"
alias cl="clear"
alias hu="homestead up"
alias hh="homestead halt"
alias nah="git reset --hard && git clean -df"
alias wip="git add . && git commit -m 'WIP'"
alias wipa="git add . && git commit --amend -m 'WIP'"
alias gempty="git commit --allow-empty -m 'Empty Commit'"
alias phpunit="./vendor/bin/phpunit"
alias nrs='npm run serve'
alias nrw='npm run watch'
alias nrd='npm run dev'
alias nrb='npm run build'
alias editzshrc='vim ~/.zshrc'
alias editalias='vim ~/.oh-my-zsh-custom/custom/aliases.zsh'
alias vimt="cd ~/Code/Tighten/\$(ls ~/Code/Tighten | fzf) && vim +GFiles"
alias vimj="cd ~/Code/JoseCanHelp/\$(ls ~/Code/JoseCanHelp | fzf) && vim +GFiles"
alias vv="vim ."
alias mutt="neomutt"
alias dockerps='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Ports}}"'
alias dp="dockerps"
alias dockerpsa='docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Ports}}"'
alias dpa="dockerpsa"
alias resetwacom="launchctl unload /Library/LaunchAgents/com.wacom.wacomtablet.plist && launchctl load -w /Library/LaunchAgents/com.wacom.wacomtablet.plist"
alias l="ls -alh"
alias src="exec zsh"
alias ..="cd .."
alias zz='z -c'      # restrict matches to subdirs of $PWD
alias zi='z -i'      # cd with interactive selection
alias zf='z -I'      # use fzf to select in multiple matches
alias zb='z -b'      # quickly cd to the parent directory
alias pb='pianobar'
alias pad='php artisan dusk'
alias jig="./vendor/bin/jigsaw"
alias to="./bin/run"
alias vimini="vim $(getPhpIni)"
alias tinkpw="php artisan tinker --execute=\"echo bcrypt('password')\" | pbcopy"
alias vim="nvim"
alias lll="ranger"
alias vimlog="nvim -V9myNvim.log ."
alias ghopen="gh repo view --web"
alias vso="valet start && valet open"
alias mfs="php artisan migrate:fresh --seed"
alias ubuntu="ssh 192.168.4.47"
alias sshdev="ssh forge@143.198.66.78"
alias sshredeeem="ssh forge@165.227.13.188"
alias forceprune="docker volume prune --force && docker system prune --force"
alias pest="./vendor/bin/pest"
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias smfs="./vendor/bin/sail artisan migrate:fresh --seed"
alias stp="./vendor/bin/sail test -p"
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
alias gdesc="git log --no-merges --pretty=format:'- %s' master.. | pbcopy"
