alias sshve="ssh root@ve.josecanhelp.com"
alias heroky="heroku"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp="git push origin HEAD"
alias gd="git diff"
alias gac="git add -A && git commit -m"
alias gs="git status"
alias artisan="php artisan"
alias art="php artisan"
alias hh="cd ~/Code/HomeHero/harvey"
alias dot="cd ~/dotfiles"
alias dq="cd ~/Code/HomeHero/Data-Queries"
alias gsa="git submodule add"
alias vs="vagrant status"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vd="vagrant destroy"
alias bfg="java -jar ~/Code/bfg.jar"
alias cda="composer dump-autoload"
alias phpunit="vendor/bin/phpunit"
alias jekyll serve="bundle exec jekyll serve --watch"
alias tower="/usr/local/bin/gittower"
alias dpostgred="docker run --name postgres -v data:/var/lib/postgresql/data -e POSTGRES_USER=perk -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=myapp -p 5432:5432 -d postgres"
alias artclear="php artisan cache:clear && php artisan config:clear && php artisan view:clear"
