alias sshve="ssh root@ve.josecanhelp.com"
alias heroky="heroku"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp="git push origin HEAD"
alias gd="git diff"
alias gac="git add -A && git commit -m"
alias gs="git status"
alias artisan="php artisan"
alias art="php artisan"
alias tt="cd ~/Code/Tighten/"
alias dot="cd ~/dotfiles"
alias gsa="git submodule add"
alias vs="vagrant status"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vd="vagrant destroy"
alias cda="composer dump-autoload"
alias dpostgres="docker run --name postgres -v data:/var/lib/postgresql/data -e POSTGRES_USER=perk -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=myapp -p 5432:5432 -d postgres"
alias artclear="php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan debugbar:clear && php artisan route:clear"
alias git="hub"
alias phpunitd="php -d xdebug.profiler_enable=on vendor/bin/phpunit"
alias cl="clear"
alias sshdo="ssh root@104.236.68.176"
alias hu="homestead up"
alias hh="homestead halt"
alias hssh="homestead ssh"
alias nah="git reset --hard && git clean -df"
alias wip="git add . && git commit -m 'WIP'"
alias wipa="git add . && git commit --amend -m 'WIP'"
alias gempty="git commit --allow-empty -m 'Empty Commit'"
alias dockerps="docker ps --format \"{{.Names}} \t {{.Status}} \t {{.Ports}}\""
alias phpunit="./vendor/bin/phpunit"
alias python='python3'
alias nrs='npm run serve'
alias editzshrc='vim ~/.zshrc'
alias editalias='vim ~/.oh-my-zsh-custom/custom/aliases.zsh'
