sshve="ssh root@ve.josecanhelp.com"
vssh="cd ~/vagrant-homehero-web; vagrant ssh"
heroky="heroku"
glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
gp="git push origin HEAD"
gd="git diff"
gac="git add -A && git commit -m"
gs="git status"
partink="php artisan tinker"
