# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"

# ------------------------------------------------------------------------------
# Zshrc
# ------------------------------------------------------------------------------
# This file configures all of the settings for zsh.
# Alias and Functions files are sourced from external paths.
# Plugins were installed via brew.
#   -- brew install zsh-autosuggestions zsh-syntax-highlighting z.lua

# zmodload zsh/zprof

# ------------------------------------------------------------------------------
# Sensitive Values
# ------------------------------------------------------------------------------
[ -f ~/.secrets ] && source ~/.secrets


# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

export PATH=${PATH}:/bin
export PATH=${PATH}:/opt/homebrew/lib
export PATH=${PATH}:/sbin
export PATH=${PATH}:/usr/bin
export PATH=${PATH}:/usr/local/aws/bin
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/opt
export PATH=${PATH}:/usr/local/opt/coreutils/libexec/gnubin
export PATH=${PATH}:/usr/local/sbin
export PATH=${PATH}:/usr/sbin
export PATH=${PATH}:~/.composer/vendor/bin
export PATH=${PATH}:~/.dotfiles/bin
export PATH=${PATH}:~/.dotfiles/bin/apache-maven-3.9.9/bin
export PATH=${PATH}:~/.dotfiles/bin/jdt-java-lang-server/bin
export PATH=${PATH}:~/.local/bin
export PATH=${PATH}:~/.rbenv/versions/bin
export PATH=${PATH}:~/nvim-osx64/bin
export PATH=${PATH}:~/go/bin
export PATH=${PATH}:/opt/homebrew/opt/mysql-client/bin
export PATH=${PATH}:/Users/jose/dotfiles/bin/nvim-macos-arm64/bin
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES # Required for iterm shell integration
export PATH="/opt/homebrew/opt/php@8.3/bin:$PATH"


# ------------------------------------------------------------------------------
# General Settings
# ------------------------------------------------------------------------------

export EDITOR=nvim
export LANG=en_US.UTF-8
export SAM_CLI_TELEMETRY=0

# ------------------------------------------------------------------------------
# Source External ZSH Files
# ------------------------------------------------------------------------------

source $HOME/dotfiles/zsh/custom/functions.zsh
source $HOME/dotfiles/zsh/custom/aliases.zsh

# ------------------------------------------------------------------------------
# Auto-Tab / Completion
# ------------------------------------------------------------------------------

autoload -Uz compinit
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # case-insensitive completion
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.

autoload bashcompinit && bashcompinit
complete -C '/usr/local/bin/aws_completer' aws

# ------------------------------------------------------------------------------
# Starship Prompt
# ------------------------------------------------------------------------------

eval "$(starship init zsh)"


# ------------------------------------------------------------------------------
# Vim Mode
# ------------------------------------------------------------------------------

bindkey -v '^?' backward-delete-char # Enable vim mode in zsh
export KEYTIMEOUT=1 # Remove mode switching delay.

# Use HJKL in auto-complete menu selection
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Edit line in Vim with CTRL-E
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line


# ------------------------------------------------------------------------------
# Z.lua Jump to Directory
# ------------------------------------------------------------------------------

# eval "$(lua /opt/homebrew/Cellar/z.lua/1.8.16/share/z.lua/z.lua --init zsh)"

# export _ZL_ROOT_MARKERS=".git,package.json,composer.json" # Jump to project root with zb


# ------------------------------------------------------------------------------
# Fzf Config
# ------------------------------------------------------------------------------

export FZF_DEFAULT_COMMAND='ag -u -g ""'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_DEFAULT_OPTS='--preview-window right:50%:noborder:hidden --color "preview-bg:234" --bind "alt-p:toggle-preview"'


# ------------------------------------------------------------------------------
# Fzf Installer Generated Config
# ------------------------------------------------------------------------------

# Setup fzf
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/usr/local/opt/fzf/bin"
fi

# Auto-completion
[[ $- == *i* ]] && source "/opt/homebrew/Cellar/fzf/0.61.1/shell/completion.zsh" 2> /dev/null

# Key bindings
source "/opt/homebrew/Cellar/fzf/0.61.1/shell/key-bindings.zsh"

# ------------------------------------------------------------------------------
# Auto Suggest Settings
# ------------------------------------------------------------------------------

ZSH_AUTOSUGGEST_STRATEGY=(history completion) # First search history, then directory
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Source autosuggestion plugin
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null

# ------------------------------------------------------------------------------
# FZF
# ------------------------------------------------------------------------------

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ------------------------------------------------------------------------------
# Auto Suggest Settings (Needs to be last)
# ------------------------------------------------------------------------------

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters

# Source syntax highlighting plugin
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home"

# Amazon Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"


# Herd injected PHP binary.
export PATH="/Users/jose/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/jose/Library/Application Support/Herd/config/php/82/"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jose/dotfiles/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jose/dotfiles/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jose/dotfiles/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jose/dotfiles/bin/google-cloud-sdk/completion.zsh.inc'; fi
