# ------------------------------------------------------------------------------
# Zshrc
# ------------------------------------------------------------------------------
# This file configures all of the settings for zsh.
# Alias and Functions files are sourced from external paths.
# Plugins were installed via brew.
#   -- brew install zsh-autosuggestions zsh-syntax-highlighting z.lua


# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/sbin
export PATH=${PATH}:/usr/bin
export PATH=${PATH}:/usr/sbin
export PATH=${PATH}:/bin
export PATH=${PATH}:/sbin
export PATH=${PATH}:~/.composer/vendor/bin
export PATH=${PATH}:/usr/local/opt/ruby/bin
export PATH=${PATH}:~/Library/Android/sdk
export PATH=${PATH}:~/Library/Android/sdk/platform-tools
export PATH=${PATH}:~/go/bin
export PATH=${PATH}:~/.dotfiles/bin


# ------------------------------------------------------------------------------
# General Settings
# ------------------------------------------------------------------------------

export EDITOR="vim"
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES # Required for iterm shell integration
export LANG=en_US.UTF-8
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# ------------------------------------------------------------------------------
# Source External ZSH Files
# ------------------------------------------------------------------------------

source $HOME/dotfiles/zsh/custom/functions.zsh
source $HOME/dotfiles/zsh/custom/aliases.zsh


# ------------------------------------------------------------------------------
# Auto-Tab / Completion
# ------------------------------------------------------------------------------

autoload -Uz compinit
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # case-insensitive completion
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.


# ------------------------------------------------------------------------------
# Pure Prompt
# ------------------------------------------------------------------------------

autoload -U promptinit; promptinit
prompt pure
zstyle :prompt:pure:git:stash show yes # show the symbol when a stash exists


# ------------------------------------------------------------------------------
# Vim Mode
# ------------------------------------------------------------------------------

bindkey -v # Enable vim mode in zsh
export KEYTIMEOUT=1 # Remove mode switching delay.

# Use HJKL in auto-complete menu selection
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Edit line in Vim with CTRL-E
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line


# ------------------------------------------------------------------------------
# Z.lua Jump to Directory
# ------------------------------------------------------------------------------

eval "$(lua /usr/local/Cellar/z.lua/1.8.7/share/z.lua/z.lua --init zsh)"
export _ZL_ROOT_MARKERS=".git,package.json,composer.json" # Jump to project root with zb


# ------------------------------------------------------------------------------
# Fzf Config
# ------------------------------------------------------------------------------

export FZF_DEFAULT_COMMAND='ag -u -g ""'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_DEFAULT_OPTS='--preview-window right:50%:noborder:hidden --color "preview-bg:234" --bind "alt-p:toggle-preview"'


# ------------------------------------------------------------------------------
# Fzf Installer Generated Config
# ------------------------------------------------------------------------------

# Setup fzf
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/usr/local/opt/fzf/bin"
fi

# Auto-completion
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.zsh" 2> /dev/null

# Key bindings
source "/usr/local/opt/fzf/shell/key-bindings.zsh"

# ------------------------------------------------------------------------------
# Auto Suggest Settings
# ------------------------------------------------------------------------------

ZSH_AUTOSUGGEST_STRATEGY=(history completion) # First search history, then directory
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Source autosuggestion plugin
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null


# ------------------------------------------------------------------------------
# FZF
# ------------------------------------------------------------------------------

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# ------------------------------------------------------------------------------
# Auto Suggest Settings (Needs to be last)
# ------------------------------------------------------------------------------

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters

# Source syntax highlighting plugin
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

